package com.belajar.session.entity.valas;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

@Entity
@Table(name = "SPM_T_SPP")
@Getter
@Setter
public class Spp {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "GEN_SPP")
    @SequenceGenerator(
            name = "GEN_SPP",
            sequenceName = "SEQ_SPP",
            initialValue = 1,
            allocationSize = 1)

    @Column(name = "ID")
    private Long id;
    @Column(name = "CREATED_BY")
    private String createdBy;
    @Column(name = "CREATED_DATE")
    private Date createdDate;
    @Column(name = "DELETED")
    private Long deleted;
    @Column(name = "MODIFIED_BY")
    private String modifiedBy;
    @Column(name = "MODIFIED_DATE")
    private Date modifiedDate;
    @Column(name = "VERSION")
    private Long version;
    @Column(name = "AKUN_SSPB")
    private String akunSSPB;
    @Column(name = "AMOUNT_NOD")
    private BigDecimal amountNod;
    @Column(name = "ATTR_KATEGORI")
    private String attrKategori;
    @Column(name = "BAST_IDS")
    private String bastIds;
    @Column(name = "BELANJA")
    private BigDecimal belanja;
    @Column(name = "BULAN_GAJI")
    private Integer bulanGaji;
    @Column(name = "ID_FO")
    private String idFo;
    @Column(name = "ID_JADWAL_BYR_KONTRAK")
    private Long idJadwalByrKontrak;
    @Column(name = "ID_KONTRAK")
    private Long idKontrak;
    @Column(name = "KODE_PPK")
    private String kdPPK;
    @Column(name = "KODE_PPSPM")
    private String kdPPSPM;
    @Column(name = "ID_SSPB")
    private Long idSSPB;
    @Column(name = "ID_SUPPLIER")
    private Long idSupplier;
    @Column(name = "ID_TUP")
    private Long idTup;
    @Column(name = "ID_UP")
    private Long idUp;
    @Column(name = "JANGKA_WAKTU_TUP")
    private Integer jangkaWaktu;
    @Column(name = "JML_PEMBAYARAN")
    private BigDecimal jmlPembayaran;
    @Column(name = "JML_PENGELUARAN")
    private BigDecimal jmlPengeluaran;
    @Column(name = "JML_POTONGAN")
    private BigDecimal jmlPotongan;
    @Column(name = "JUMLAH_SSPB")
    private BigDecimal jumlahSSPB;
    @Column(name = "JUMLAH_TUP")
    private BigDecimal jumlahTup;
    @Column(name = "KD_CARA_BAYAR")
    private String kdCaraBayar;
    @Column(name = "KD_CARA_PENARIKAN")
    private String kdCaraPenarikan;
    @Column(name = "KODE_GLP_JURNAL_SPM")
    private String kdGlpJurnalSpm;
    @Column(name = "KODE_GLP_JURNAL_SPP")
    private String kdGlpJurnalSpp;
    @Column(name = "KD_JATUH_TEMPO")
    private String kdJatuhTempo;
    @Column(name = "KD_JNS_BAYAR")
    private String kdJnsBayar;
    @Column(name = "KODE_JENIS_PEGAWAI")
    private String kdJnsPegawai;
    @Column(name = "KD_JNS_SPP")
    private String kdJnsSpp;
    @Column(name = "KD_KPP")
    private String kdKpp;
    @Column(name = "KD_KPPN")
    private String kdKppn;
    @Column(name = "KD_PENARIKAN_DANA")
    private String kdPenarikanDana;
    @Column(name = "KD_SATKER")
    private String kdSatker;
    @Column(name = "KD_SIFAT_BAYAR")
    private String kdSifatBayar;
    @Column(name = "KD_VALAS")
    private String kdValas;
    @Column(name = "KEMBALI_HIBAH")
    private BigDecimal kembaliHibah;
    @Column(name = "KODE_KEGIATAN_SSPB")
    private String kodeKegiatanSSPB;
    @Column(name = "KODE_OUTPUT_SSPB")
    private String kodeOutputSSPB;
    @Column(name = "KODE_PROGRAM_SSPB")
    private String kodeProgramSSPB;
    @Column(name = "KODE_UNIK")
    private String kodeUnik;
    @Column(name = "KOMPEN_POT_SPMKP")
    private BigDecimal kompenPotSpmkp;
    @Column(name = "KOMPEN_TRANSFER")
    private BigDecimal kompenTransfer;
    @Column(name = "KOMPENSASI_UM")
    private BigDecimal kompensasiUm;
    @Column(name = "KURS_NOD")
    private BigDecimal kursNod;
    @Column(name = "NAMA_FILE")
    private String namaFile;
    @Column(name = "NAMA_PPK")
    private String namaPpk;
    @Column(name = "NAMA_PPSPM")
    private String namaPpspm;
    @Column(name = "NILAI_APLIKASI")
    private BigDecimal nilaiAplikasi;
    @Column(name = "NILAI_BAST")
    private BigDecimal nilaiBast;
    @Column(name = "NILAI_KEMBALI")
    private BigDecimal nilaiKembali;
    @Column(name = "NILAI_POTONGAN")
    private BigDecimal nilaiPotongan;
    @Column(name = "NILAI_REG_INV")
    private BigDecimal nilaiRegInv;
    @Column(name = "NILAI_RUPIAH")
    private BigDecimal nilaiRupiah;
    @Column(name = "NILAI_SP2B")
    private BigDecimal nilaiSp2b;
    @Column(name = "NILAI_SP2D")
    private BigDecimal nilaiSp2d;
    @Column(name = "NILAI_SPM")
    private BigDecimal nilaiSpm;
    @Column(name = "NILAI_TUKAR")
    private BigDecimal nilaiTukar;
    @Column(name = "NILAI_UP")
    private BigDecimal nilaiUp;
    @Column(name = "NIP_PPK")
    private String nipPpk;
    @Column(name = "NIP_PPSPM")
    private String nipPpspm;
    @Column(name = "NO_APLIKASI")
    private String noAplikasi;
    @Column(name = "NO_DIPA")
    private String noDipa;
    @Column(name = "NO_DIPA_SSPB")
    private String noDipaSSPB;
    @Column(name = "NO_GAJI")
    private String nogaji;
    @Column(name = "NO_NOD")
    private String noNod;
    @Column(name = "NO_PENGESAHAN")
    private String noPengesahan;
    @Column(name = "NO_PENGESHANAN_SSPB")
    private String noPengesahanSSPB;
    @Column(name = "NO_REG_INV")
    private String noRegInv;
    @Column(name = "NO_REGISTER")
    private String noRegister;
    @Column(name = "NO_REKSUS")
    private String noReksus;
    @Column(name = "NO_SSPB")
    private String noSSPB;
    @Column(name = "NO_SP2B")
    private String noSp2b;
    @Column(name = "NO_SP2D")
    private String noSp2d;
    @Column(name = "NO_SP3HL_BJS")
    private String noSp3hlBjs;
    @Column(name = "NO_SPM")
    private String noSpm;
    @Column(name = "NO_SPP")
    private String noSpp;
    @Column(name = "NO_SPP2")
    private String noSpp2;
    @Column(name = "NO_TUP")
    private String noTup;
    @Column(name = "NO_UP")
    private String noUp;
    @Column(name = "NO_WA")
    private String noWa;
    @Column(name = "NOMOR_BAST")
    private String nomorBast;
    @Column(name = "NOP")
    private String nop;
    @Column(name = "NPWP2")
    private String npwp2;
    @Column(name = "PAYMENT_TERMS")
    private String paymentTerms;
    @Column(name = "PEMOTONGAN_RETENSI")
    private BigDecimal pemotonganRetensi;
    @Column(name = "PENDAPATAN")
    private BigDecimal pendapatan;
    @Column(name = "PERIODE_TRIWULAN")
    private String periodeTriwulan;
    @Column(name = "PORSI_DISETOR")
    private BigDecimal porsiDisetor;
    @Column(name = "PORSI_TIDAK_DISETOR")
    private BigDecimal porsiTidakDisetor;
    @Column(name = "SALDO_AKHIR")
    private BigDecimal saldoAkhir;
    @Column(name = "SALDO_AKHIR_HIBAH")
    private BigDecimal saldoAkhirHibah;
    @Column(name = "SALDO_AWAL")
    private BigDecimal saldoAwal;
    @Column(name = "SB_DATA")
    private String sbData;
    @Column(name = "SISA_HIBAH")
    private BigDecimal sisaHibah;
    @Column(name = "STS_DATA")
    private String stsData;
    @Column(name = "KODE_SUMBER_DANA")
    private String kdSumberDana;
    @Column(name = "TGL_ADK_SPM")
    private Date tglAdkSpm;
    @Column(name = "TGL_ADK_SPP")
    private Date tglAdkSpp;
    @Column(name = "TGL_APLIKASI")
    private Date tglAplikasi;
    @Column(name = "TGL_BUKU")
    private Date tglBuku;
    @Column(name = "TGL_DIPA")
    private Date tglDipa;
    @Column(name = "TGL_JATUH_TEMPO_TUP")
    private Date tglJatuhTempo;
    @Column(name = "TGL_KURS")
    private Date tglKurs;
    @Column(name = "TGL_KURS_NOD")
    private Date tglKursNod;
    @Column(name = "TGL_NOD")
    private Date tglNod;
    @Column(name = "TGL_PEMBAYARAN")
    private Date tglPembayaran;
    @Column(name = "TGL_PENGESAHAN")
    private Date tglPengesahan;
    @Column(name = "TGL_PENGESAHAN_SSPB")
    private Date tglPengesahanSSPB;
    @Column(name = "TGL_REG_INV")
    private Date tglRegInv;
    @Column(name = "TGL_REGISTER")
    private Date tglRegister;
    @Column(name = "TGL_SSPB")
    private Date tglSSPB;
    @Column(name = "TGL_SP2B")
    private Date tglSp2b;
    @Column(name = "TGL_SP2D")
    private Date tglSp2d;
    @Column(name = "TGL_SP3HL_BJS")
    private Date tglSp3hlBjs;
    @Column(name = "TGL_SPM")
    private Date tglSpm;
    @Column(name = "TGL_SPP")
    private Date tglSpp;
    @Column(name = "TGL_TUP")
    private Date tglTup;
    @Column(name = "TGL_UP")
    private Date tglUp;
    @Column(name = "TGL_WA")
    private Date tglWa;
    @Column(name = "THN_ANG")
    private String thnAng;
    @Column(name = "THN_PAJAK")
    private String thnPajak;
    @Column(name = "TIPE_INVOICE")
    private String tipeInvoice;
    @Column(name = "TIPE_KURS")
    private String tipeKurs;
    @Column(name = "URAIAN")
    private String uraian;
    @Column(name = "URAIAN_PEMBAYARAN")
    private String uraianPembayaran;
    @Column(name = "NILAI_KONTRAK_PDN")
    private BigDecimal nilaiKontrakPdn;
    @Column(name = "NILAI_KONTRAK_PDP")
    private BigDecimal nilaiKontrakPdp;
    @Column(name = "NILAI_KONTRAK_PLN")
    private BigDecimal nilaiKontrakPln;
    @Column(name = "PEMBAYARAN_PENDAMPING")
    private BigDecimal pembayaranPendamping;
    @Column(name = "PORSI_SETOR_SAAT_INI")
    private BigDecimal porsiDisetorSaatIni;
    @Column(name = "PORSI_TDK_SETOR_SAAT_INI")
    private BigDecimal porsiTidakDisetorSaatIni;
    @Column(name = "NO_KONTRAK")
    private String noKontrak;
    @Column(name = "STATUS_APD")
    private String statusAPD;
    @Column(name = "JNS_SPP_KOREKSI")
    private String koreksiJenisSpp;
    @Column(name = "NO_SPP_KOREKSI")
    private String koreksiNoSpp;
    @Column(name = "TGL_SPP_KOREKSI")
    private Date koreksiTglSpp;
    @Column(name = "NILAI_KONTRAK_APD")
    private BigDecimal nilaiKontrakAPD;
    @Column(name = "ID_SPTB")
    private String idSptbSpp;
    @Column(name = "ID_SPP_YG_DIKOREKSI")
    private Long idSppTerkoreksi;
    @Column(name = "KOREKSI_FLAG")
    private Boolean koreksiFlag;
    @Column(name = "ID_JADWAL_RETENSI")
    private String idJadwalRetensi;
    @Column(name = "ID_KONTRAK_RETENSI")
    private String idKontrakRetensi;
    @Column(name = "TGL_SPM_KOREKSI")
    private Date koreksiTglSpm;
    @Column(name = "NILAI_TUKAR_SP2D")
    private BigDecimal nilaiTukarSp2d;
    @Column(name = "TEMPAT_CETAK_SPM")
    private String tempatCetakSpm;
    @Column(name = "TEMPAT_CETAK_SPP")
    private String tempatCetakSpp;
    @Column(name = "TGL_CETAK_SPM")
    private Date tglCetakSpm;
    @Column(name = "TGL_CETAK_SPP")
    private Date tglCetakSpp;
    @Column(name = "REQ_ID_SPM")
    private String reqIdSpm;
    @Column(name = "REQ_ID_SPP")
    private String reqIdSpp;
    @Column(name = "ID_RENKAS")
    private String idRenkas;
    @Column(name = "TGL_SP2D_KOREKSI")
    private Date tglSp2dKoreksi;
}
